name: deploy

on:
  repository_dispatch:
    types: [deploy-service]

jobs:
  deploy:
    runs-on: ubuntu-latest

    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Install Terraform
        run: |
          sudo apt-get install unzip
          wget https://releases.hashicorp.com/terraform/1.0.6/terraform_1.0.6_linux_amd64.zip
          unzip terraform_1.0.6_linux_amd64.zip
          sudo mv terraform /usr/local/bin/

      - name: Run Deploy
        run: ./bin/deploy ${{ github.event.client_payload.environment }}
